add notice for require plugins
lubusIN/woocommerce-stats-by-currency pull request #4
Opened 2020-04-22 11:38 UTC by NaveenKharwar

2020-04-23 05:00 UTC, ajitbohra requested changes
seems like accidental PR we are deleting the plugin file!

2020-04-23 05:24 UTC, NaveenKharwar commented
> seems like accidental PR we are deleting the plugin file!

Yes, I fixed it now you can review.

2020-04-24 09:46 UTC, ajitbohra requested changes
We can simplify this

``` php
/**
 * Check required plugins
 *
 * @return void
 */
function wsbc_required_plugins() {
	$activated = (array) get_option( 'active_plugins', array() );
	$required  = array(
		'woocommerce/woocommerce.php',
		'woocommerce-product-price-based-on-countries/woocommerce-product-price-based-on-countries.php'
	);

	$required_plugins_activated = count( array_intersect($activated, $required) ) == count( $required );

    if ( !$required_plugins_activated  ) {
		$msg_text    = 'Sorry, This plugin requires <strong>WooCommerce</strong> and <strong>WooCommerce Price Based on Country</strong> plugins to work.';
		$plugins_link   = sprintf( '<a href="%s">Install Plugins</a>', admin_url('plugins.php') );
		$dashboard_link = sprintf( '<a href="%s">Dashboard</a>', admin_url() );
		$msg            = sprintf( '%s <br/><br/> %s | %s', $msg_text, $plugins_link, $dashboard_link );

		wp_die( $msg );
    }
}
register_activation_hook( __FILE__, 'wsbc_required_plugins' );

```

2020-04-24 09:46 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +    if ( is_admin() && current_user_can( 'activate_plugins' ) &&  !is_plugin_active( 'woocommerce/woocommerce.php' )  ) {
- `admin_init` hooks will only run on admin so `is_admin()` check not required
- only users with `activate_plugins` can activate plugins `current_user_can( 'activate_plugins' )` check here redundant
- We are only checking for `WooCommerce` other dependent plugin `WooCommerce Price By Country` is missing

2020-04-24 09:46 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +        add_action( 'admin_notices', 'wsbc_notice' );
We can use `wp_die( 'Plugins required msg' )` to simplify this

2020-04-24 09:46 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +// Admin Notice
Good if we can follow comment style 

```
/**
* Function description
*/
```

2020-04-26 11:31 UTC, ajitbohra requested changes
Also, code feels a bit uncomfortable we can extract CSS and HTML into a separate `HTML view` to simplifying this.

2020-04-26 11:31 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +                                }
let's simplify this for better design & style. moving border to body/ error wrapper

```suggestion
                                #error-page {
                                    border-left: solid 5px #dc3232;
                                }
```

<img width="827" alt="die_msg" src="https://user-images.githubusercontent.com/1039236/80305729-3af65b00-87dc-11ea-962a-d0402b6b2579.png">

2020-04-26 11:31 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +        $msg_text       = '<p>Sorry, This plugin requires <strong>WooCommerce</strong> and <strong>WooCommerce Price Based on Country</strong> plugins to work. Learn how to install <strong>WooCommerc
Currently, the plugin doesn't require setup guide and we don't have one. so let's remove `Learn how to install WooCommerce Stats By Currency in the guide.`

2020-04-26 16:31 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +	$activated = (array) get_option( 'active_plugins', array() );
```suggestion
	$activated = apply_filters( 'active_plugins', (array) get_option( 'active_plugins', array() ) );
```

Let's respect the data filtering.

2020-04-27 13:58 UTC, ajitbohra requested changes

2020-04-27 13:58 UTC, ajitbohra commented on includes/view/notice.php
> +
Additional space

2020-04-27 13:58 UTC, ajitbohra commented on woocommerce-stats-by-currency.php
> +		'woocommerce/woocommerce.php',
No need to check for `woocommerce` as `woocommerce-product-price-based-on-countries` will have it as a dependency.

2020-04-27 13:58 UTC, ajitbohra commented on includes/view/notice.php
> +    <p>Sorry, This plugin requires <strong>WooCommerce</strong> and <strong>WooCommerce Price Based on Country</strong> plugins installed and activated to work.</p>
No need to check for woocommerce as woocommerce-product-price-based-on-countries will have it as a dependency.

2020-04-27 13:58 UTC, ajitbohra commented
@NaveenKharwar last few changes are we are good to merge this :)

2020-04-28 17:14 UTC, ajitbohra requested changes

2020-04-28 17:14 UTC, ajitbohra commented on includes/view/notice.php
> +    <p>Sorry, This plugin requires <strong>WooCommerce Price Based on Country</strong> plugins installed and activated to work.</p>
Sting here is not translatable!

2020-04-28 17:14 UTC, ajitbohra commented on includes/view/notice.php
> +$pluginpage = admin_url('plugins.php');
use snake case for the name

```suggestion
$dashboard_url = admin_url();
$plugins_url   = admin_url('plugins.php');
```

2020-04-29 05:40 UTC, merged